#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 30 16:24:30 2023

@author: alizeekastler
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Define your pre and post-processing average gray values for the baseline condition
baseline_pre = [65.6, 80.9, 60.2, 58.5]
baseline_post = [66.4, 79.9, 61.2, 61.6]

# Define your pre and post-processing average gray values for the heat condition
heat_pre = [66.1, 87.5, 55.9, 71.0]
heat_post = [58.5, 74.0, 41.9, 66.4]



# Calculate the diff in mean gray value
heat_diff = np.array(heat_pre) - np.array(heat_post)
baseline_diff = np.array(baseline_pre) - np.array(baseline_post)
data = [baseline_diff, heat_diff]


plt.figure(figsize=(3, 10))
ax=sns.boxplot(data = data,color ='whitesmoke', linewidth =1, showfliers=False)
ax=sns.stripplot(data = data, palette = ['#aaa4c8', '#452775'], size=6, jitter=True, edgecolor="gray")
ax.set_xticklabels(['Baseline', 'Heat'])
   
# Add labels and a title
plt.ylabel('Δ Mean Gray Value (pre-post)', fontsize = 16)
plt.xticks(fontsize=16)
plt.yticks(fontsize=14)
plt.ylim(-2,20)

# Remove the top and right spines (outlines)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)

# Show the plot
plt.show()




