#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 13 18:08:47 2023

@author: alizeekastler
"""

# -----------------------------------------------------------------------------
lib_path = r'/Users/alizeekastler/Documents/GitHub/Social_Pain/libs'
#lib_path = r'C:/Repos/Social_Pain/libs'
import sys
sys.path.append(lib_path)

base_path = r'/Volumes/T7 Touch/Behaviour_Heat_Gradient'
#base_path = r'S:/WIBR_Dreosti_Lab/Alizee/Behaviour_Heat_Gradient'



# Import useful libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import fdrcorrection


from sklearn.cluster import KMeans


from sklearn import datasets
 

import glob

# Specify Analysis folder

AnalysisFolder = base_path + '/Gradient_Social/Analysis'
FigureFolder = base_path + '/Gradient_Social/Figures'

# Find all the npz files saved for each group and fish with all the information
npzFiles = glob.glob(AnalysisFolder+'/*.npz')

# Calculate how many files
numFiles = np.size(npzFiles, 0)
# Allocate space for summary data
cat_ALL = np.zeros(numFiles)
BPS_NS_ALL = np.zeros(numFiles)
BPS_S_ALL = np.zeros(numFiles)
avgPosition_NS_ALL = np.zeros(numFiles)
avgPosition_S_ALL = np.zeros(numFiles)
avgdistPerBout_NS_ALL = np.zeros(numFiles)
avgdistPerBout_S_ALL = np.zeros(numFiles)
Turns_NS_ALL = np.zeros(numFiles)
Turns_S_ALL = np.zeros(numFiles)
FSwim_NS_ALL = np.zeros(numFiles)
FSwim_S_ALL = np.zeros(numFiles)
numFreezes_NS_ALL = np.zeros(numFiles)
numFreezes_S_ALL = np.zeros(numFiles)
DistanceT_NS_ALL = np.zeros(numFiles)
DistanceT_S_ALL = np.zeros(numFiles)
                           
SummaryAll = []

# Go through all the files contained in the analysis folder
for f, filename in enumerate(npzFiles):

    # Load each npz file
    dataobject = np.load(filename, allow_pickle = True)
    
    # Extract from the npz file 
    cat = dataobject['cat']
    BPS_NS = dataobject['BPS_NS']   
    BPS_S = dataobject['BPS_S']

    Turns_NS = dataobject['Turns_NS']
    Turns_S = dataobject['Turns_S']
    
    Freezes_NS = dataobject['Freezes_NS']
    Freezes_S = dataobject['Freezes_S']
    
    numFreezes_NS = dataobject['numFreezes_NS']
    numFreezes_S = dataobject['numFreezes_S']

    DistanceT_NS = dataobject['DistanceT_NS']
    DistanceT_S = dataobject['DistanceT_S']
    
    avgPosition_NS = dataobject['avgPosition_NS']
    avgPosition_S = dataobject['avgPosition_S']
    
    avgdistPerBout_NS = dataobject['avgdistPerBout_NS']
    avgdistPerBout_S = dataobject['avgdistPerBout_S']
    
    # Make an array with all summary stats
    cat_ALL[f]= cat
    BPS_NS_ALL[f] = BPS_NS
    BPS_S_ALL[f] = BPS_S
    numFreezes_NS_ALL[f] = numFreezes_NS
    numFreezes_S_ALL[f] = numFreezes_S
    
    avgPosition_NS_ALL[f] = avgPosition_NS
    avgPosition_S_ALL[f] = avgPosition_S
    #mPosition_NS_ALL[f] = mPosition_NS
    #mPosition_S_ALL[f] = mPosition_S
    avgdistPerBout_NS_ALL[f] = avgdistPerBout_NS
    avgdistPerBout_S_ALL[f] = avgdistPerBout_S
    #avg_cue_motion_ALL[f] = avg_cue_motion
    Turns_NS_ALL[f] = Turns_NS
    Turns_S_ALL[f] = Turns_S
    
    DistanceT_NS_ALL[f] = DistanceT_NS
    DistanceT_S_ALL[f] = DistanceT_S

    SummaryAll.append([float(BPS_NS), float(avgdistPerBout_NS),float(DistanceT_NS),float(Turns_NS), float(numFreezes_NS)])

dfAll=pd.DataFrame(SummaryAll,columns=['BoutsPerSecond','distPerBout', 'distTravelled', 'Turn','Freezes'])



# #sns.barplot(dfAll['Condition'], dfAll['BoutsPerSecond'])
# #sns.barplot(dfAll, hue = dfAll['Condition'])
# ax = dfAll.plot(x=['BoutsPerSecond','distPerBout', 'distTravelled', 'Turn','Freezes'], kind="bar", hue= dfAll['Condition'], rot=0)

# high = dfAll.loc[dfAll['Condition']==1]

# plt.plot(high)

XM_values = np.column_stack((avgPosition_NS_ALL, avgPosition_S_ALL))

fig = plt.figure(figsize=(10, 6))
x = XM_values[:, 0]
y = XM_values[:, 1]

plt.scatter(x, y, marker=".")
plt.xlabel('Non Social')
plt.ylabel('Social')
plt.title('AvgPosition')
plt.show()


n_clusters = 4

kmeans = KMeans(n_clusters=4, random_state=0, n_init=10).fit(XM_values)

fig = plt.figure(figsize=(10, 6))
fig.subplots_adjust()
colors = ["Indigo", "orchid", "darkorange", 'Blue']

k = kmeans.labels_
center = kmeans.cluster_centers_


# KMeans
ax = fig.add_subplot(1, 3, 1)

for k, col in zip(range(n_clusters), colors):
    my_members = kmeans.labels_ == k
    cluster_center = kmeans.cluster_centers_[k]
    ax.plot(XM_values[my_members, 0], XM_values[my_members, 1], "w", markerfacecolor=col, marker=".")
    ax.plot(
        cluster_center[0],
        cluster_center[1],
        "o",
        markerfacecolor=col,
        markeredgecolor="k",
        markersize=6,
    )
ax.set_title("KMeans")
ax.set_xlabel('Non Social')
ax.set_ylabel('Social')


labels = pd.DataFrame(kmeans.labels_)
dfAll2 = pd.concat([dfAll, labels], axis=1)

dfAll2.columns = ['BoutsPerSecond','distPerBout', 'distTravelled', 'Turn','Freezes','Cluster']


dfAll2=pd.DataFrame(dfAll2,columns=['Cluster','BoutsPerSecond','distPerBout', 'distTravelled', 'Turn','Freezes'])




cluster1 = dfAll2.loc[dfAll2['Cluster']==3]
#cluster1 = cluster1.drop(['Cluster'], axis=1)

cluster2 = dfAll2.loc[dfAll2['Cluster']==2]
#cluster2 = cluster2.drop(['Cluster'], axis=1)

cluster3 = dfAll2.loc[dfAll2['Cluster']==1]
#cluster3 = cluster3.drop(['Cluster'], axis=1)

clusters = pd.concat([cluster1, cluster2, cluster3], axis=0)




# Plot histograms for each column based on 'Condition'
for column in clusters.columns[1:]:
    plt.figure()
    sns.histplot(data=clusters, x=column, hue='Cluster', multiple='stack', kde=True)
    #plt.xlim((0,4))
    plt.title(f'Histogram of {column} by Cluster')

plt.show()


# Plot bar charts for each column based on 'Condition'
for i, column in enumerate(dfAll2.columns[1:]):
    plt.subplot(2, 3, i+1)
    sns.barplot(data=dfAll2, x='Cluster', y=column)
    plt.title(f'{column} by Cluster')

# Adjust the layout
plt.tight_layout()




BaselineFolder = base_path + '/NoStim_15min/Analysis'

# Find all the npz files saved for each group and fish with all the information
npzFilesB = glob.glob(BaselineFolder+'/*.npz')

# Calculate how many files
numFiles = np.size(npzFilesB, 0)
# Allocate space for summary data
BPS_NS_ALL = np.zeros(numFiles)
avgPosition_NS_ALL = np.zeros(numFiles)
avgdistPerBout_NS_ALL = np.zeros(numFiles)
Turns_NS_ALL = np.zeros(numFiles)
FSwim_NS_ALL = np.zeros(numFiles)
numFreezes_NS_ALL = np.zeros(numFiles)
DistanceT_NS_ALL = np.zeros(numFiles)
                           
Baseline = []

# Go through all the files contained in the analysis folder
for f, filename in enumerate(npzFilesB):

    # Load each npz file
    dataobject = np.load(filename, allow_pickle = True)
    
    # Extract from the npz file 
    
    BPS_NS = dataobject['BPS_S']   
   
    Turns_NS = dataobject['Turns_S']

    Freezes_NS = dataobject['Freezes_S']
    
    numFreezes_NS = dataobject['numFreezes_S']

    DistanceT_NS = dataobject['DistanceT_S']
    
    #avgPosition_NS = dataobject['avgPosition_S']
    
    avgdistPerBout_NS = dataobject['avgdistPerBout_S']
    
    # Make an array with all summary stats
    BPS_NS_ALL[f] = BPS_NS
    numFreezes_NS_ALL[f] = numFreezes_NS
    
    avgPosition_NS_ALL[f] = avgPosition_NS
    avgdistPerBout_NS_ALL[f] = avgdistPerBout_NS
    Turns_NS_ALL[f] = Turns_NS
    
    DistanceT_NS_ALL[f] = DistanceT_NS

    Baseline.append([float(BPS_NS), float(avgdistPerBout_NS),float(DistanceT_NS),float(Turns_NS), float(numFreezes_NS)])

Bas=pd.DataFrame(Baseline,columns=['BoutsPerSecond','distPerBout', 'distTravelled', 'Turn','Freezes'])



# perform mannwhitney with bonferroni correction
def mann_whitney_all_vs_Bas(df_Baseline, df):
    """
    Perform Mann-Whitney U tests comparing each condition to the Baseline
    
    Parameters:
        df (pandas.DataFrame): Input dataframe containing the behavioral data.

    Returns:
        pandas.DataFrame: Dataframe containing the p-values and FDR-corrected p-values for each condition and column.
    """
    # Create empty dataframe to store results
    stats_df = pd.DataFrame()

    # Perform Mann-Whitney U test for each genotype compared to "Scrambled" for all columns
    for col_name in df.columns:
            group1 = [df_Baseline, col_name]
            group2 = [df, col_name]
            _, pvalue = mannwhitneyu(group1, group2, alternative="two-sided")
            stats_df = stats_df.append({ "Column": col_name, "pvalue": pvalue}, ignore_index=True)

    # Correct p-values for multiple comparisons using FDR
    stats_df["pvalue_corr"] = fdrcorrection(stats_df["pvalue"])[1]

    return stats_df

MannW_results_all = mann_whitney_all_vs_Bas(Bas, dfAll)






# extract Baseline ( no stimuli)
def data_proc(cluster):
    cluster_zscore = cluster.copy()
    
    numeric_cols = cluster.select_dtypes(include=[np.number]).columns 
# compute mean and SD
    BMean=Bas.mean()
    Bstd=Bas.std()
# normalise dataframe
    for col in numeric_cols:
        cluster_zscore[col]=(cluster[col]-BMean[col])/Bstd[col]
    return cluster_zscore

cluster1_zscore= data_proc(cluster1).mean()
cluster2_zscore= data_proc(cluster2).mean()  
cluster3_zscore= data_proc(cluster3).mean()  

Zclusters = pd.concat([cluster1_zscore, cluster2_zscore, cluster3_zscore], axis=1)
Zclusters = Zclusters.T


fingerprint =plt.figure(figsize= (14,5))

ax=sns.heatmap(Zclusters,vmin=-1,vmax=1,cmap='PuOr', linewidth=0.5, square = True, cbar_kws={'shrink':0.8})
ax.set(xlabel='', ylabel='')
ax.xaxis.tick_top()
plt.xticks(rotation=20, fontsize = 18)
plt.yticks(rotation= 360, fontsize=18)



fingerprint.savefig(base_path + '/clusters.eps', format='eps', dpi=300,bbox_inches= 'tight')
#fingerprint.savefig(base_path + '/RE-Exposed.png', dpi=300, bbox_inches='tight')
              

hclusters = []
hclusters.append([avgPosition_NS_ALL, avgPosition_S_ALL,cat_ALL])
hclusters = np.array(hclusters)



x_a = hclusters[:,0][hclusters[:,2]==1]
y_a = hclusters[:,1][hclusters[:,2]==1]

x_b = hclusters[:,0][hclusters[:,2]==2]
y_b = hclusters[:,1][hclusters[:,2]==2]

x_c = hclusters[:,0][hclusters[:,2]==3]
y_c = hclusters[:,1][hclusters[:,2]==3]

x_d = hclusters[:,0][hclusters[:,2]==4]
y_d = hclusters[:,1][hclusters[:,2]==4]


fig = plt.figure(figsize=(6, 10))

plt.scatter(x_a, y_a, marker=".", color = 'red')
plt.scatter(x_b, y_b, marker=".", color = 'blue')
plt.scatter(x_c, y_c, marker=".", color = 'green')
plt.scatter(x_d, y_d, marker=".", color = 'orange')

plt.xlabel('Non Social')
plt.ylabel('Social')
plt.title('AvgPosition')
plt.show()





